---
- name: Delete item
  ansible.builtin.command:
    cmd: op item delete '{{ onepassword_item.title }}' --vault "{{ onepassword_vault }}"
  become: true
  become_user: "{{ onepassword_become_user }}"
  delegate_to: localhost
  changed_when: true
  # no_log: true

- name: Clear item result fact
  ansible.builtin.set_fact:
    onepassword_item_result: {}
