---
- name: Check Item Exists (Basic)
  ansible.builtin.command:
    cmd: 'op item get ''{{ onepassword_item_title }}'' --vault "{{ onepassword_vault }}" --format json'
  register: onepassword_find_item_result
  become: true
  become_user: "{{ onepassword_become_user }}"
  delegate_to: localhost
  failed_when: false
  changed_when: false
  no_log: true
  until: onepassword_find_item_result is defined
  retries: 3
  delay: 2
  when: not full_details | default(false)

- name: Check Item Exists (Full Details)
  ansible.builtin.command:
    cmd: >-
      op item get '{{ onepassword_item_title }}'
      --vault "{{ onepassword_vault }}"
      --reveal
      --format json
  register: onepassword_find_item_result
  become: true
  become_user: "{{ onepassword_become_user }}"
  delegate_to: localhost
  failed_when: false
  changed_when: false
  no_log: true
  until: onepassword_find_item_result is defined
  retries: 3
  delay: 2
  when: full_details | default(false)

- name: Set Item Existence Facts
  ansible.builtin.set_fact:
    onepassword_item_exists: "{{ onepassword_find_item_result.rc == 0 }}"
    onepassword_item_id: >-
      {{
        (onepassword_find_item_result.stdout | from_json).id
        if onepassword_find_item_result.rc == 0 and onepassword_find_item_result.stdout | length > 0
        else ''
      }}
    onepassword_found_item_details: >-
      {{
        onepassword_find_item_result.stdout | from_json
        if onepassword_find_item_result.rc == 0 and onepassword_find_item_result.stdout | length > 0
        else {}
      }}
  no_log: true
