---
- name: Read item
  ansible.builtin.command:
    cmd: >-
      op item get '{{ onepassword_item.title }}'
      --vault "{{ onepassword_vault }}"
      --reveal
      --format json
  become: true
  become_user: "{{ onepassword_become_user }}"
  delegate_to: localhost
  register: _onepassword_read_result
  changed_when: false
  failed_when: false
  no_log: true

- name: Fail if item not found
  ansible.builtin.fail:
    msg: >-
      1Password item '{{ onepassword_item.title }}' not found in vault '{{ onepassword_vault }}'.
      This item must be created manually before running this play.
  when: _onepassword_read_result.rc != 0

- name: Set item result fact
  ansible.builtin.set_fact:
    onepassword_item_result: "{{ _onepassword_read_result.stdout | from_json }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ ansible_play_hosts }}"
  no_log: true
