---
# Creates an OS admin user with password, sudo, and a static SSH key.
# Used for human admin users like kate.

- name: Ensure admin user password exists in 1Password
  no_log: true
  ansible.builtin.include_role:
    name: onepassword
  vars:
    onepassword_action: upsert
    onepassword_item:
      title: "{{ os_user_admin_password_item_title }}"
      username: "{{ os_user_admin_name }}"

- name: Create OS admin user
  become: true
  no_log: true
  ansible.builtin.user:
    name: "{{ os_user_admin_name }}"
    shell: /bin/bash
    password: >-
      {{
        onepassword_item_result.fields |
        selectattr('id', 'equalto', 'password') |
        map(attribute='value') | first
        | password_hash(salt=os_user_admin_password_salt, hashtype='sha512')
      }}

- name: Grant admin user sudo
  become: true
  community.general.sudoers:
    name: "{{ os_user_admin_name }}"
    commands: ALL
    runas: ALL
    state: present
    user: "{{ os_user_admin_name }}"
    nopassword: false

- name: Authorize sysadmin SSH key for admin user
  ansible.builtin.include_role:
    name: identity
    tasks_from: static_key
  vars:
    identity_static_key_user: "{{ os_user_admin_name }}"
    identity_static_key_public_key: "{{ sysadmin_public_key }}"
