---
# Creates a passwordless OS service account with sudo access.
# Used for automation users like opentofu and ansible.

- name: Create OS user - {{ os_user_name }}
  become: true
  ansible.builtin.user:
    name: "{{ os_user_name }}"
    shell: /bin/bash

- name: Grant sudo - {{ os_user_name }}
  become: true
  community.general.sudoers:
    name: "{{ os_user_name }}"
    commands: ALL
    runas: ALL
    state: present
    user: "{{ os_user_name }}"
    nopassword: true
