---
- name: Restart pihole dns
  become: true
  ansible.builtin.systemd:
    name: pihole-FTL
    state: restarted

- name: Update pihole gravity
  become: true
  ansible.builtin.command:
    cmd: pihole updateGravity

- name: Restart nebula-sync
  become: true
  ansible.builtin.systemd:
    name: nebula-sync.timer
    state: restarted
    daemon_reload: true

- name: Restart systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
