variable "kate_email" {
  type        = string
  description = "Sarge's email"
}

variable "proxmox_root_password" {
  type        = string
  description = "Root password"
}

variable "proxmox_endpoint" {
  type        = string
  description = "IP address to access Proxmox (including Port)"
}

variable "proxmox_api_token" {
  type        = string
  description = "API Token to access Proxmox"
  sensitive   = true
}

variable "proxmox_node_1" {
  type        = string
  description = "Hostname of the node you are acting on"
}

variable "proxmox_bridge_port" {
  type        = string
  description = "Name of the bridge port vmbr0 uses in your initial install of Proxmox (i.e. 'enp5s0'"
}

variable "proxmox_image_datastore" {
  type        = string
  description = "Name/ID of the datastore that retains ISOs and CT templates (i.e. 'local')"
}

variable "proxmox_vm_ct_datastore" {
  type        = string
  description = "Name/ID of the datastore that retains VM and CT disks (i.e. 'local-lvm')"
}

variable "proxmox_ip_address" {
  type        = string
  description = "IP Address for the parent Proxmox instance"
}

variable "proxmox_gateway" {
  type        = string
  description = "IP Address for the parent Proxmox gateway"
}

variable "proxmox_import_enabled" {
  type        = bool
  description = "For use with test environments vs production during import phase"
}

variable "proxmox_dns_cf_token" {
  type        = string
  description = "Cloudflare token for DNS letsencrypt plugin"
}

variable "proxmox_mac_prefix" {
  type        = string
  description = "Prefix for autogenerated MAC addresses"
}

variable "kate_public_key" {
  type        = string
  description = "Public key to log in via ssh"
}

variable "proxmox_pihole_root_password" {
  type        = string
  description = "Password for Pihole root user"
}

variable "proxmox_homepage_root_password" {
  type        = string
  description = "Password for Pihole root user"
}

variable "proxmox_nginx_proxy_manager_root_password" {
  type        = string
  description = "Password for NGINX Proxy Manager root user"
}

variable "proxmox_ubuntu_server_2024_template_root_password" {
  type        = string
  description = "Password for Ubuntu Server 2024 template root user"
}

variable "proxmox_gitlab_root_password" {
  type        = string
  description = "Password for Gitlab root user"
}

variable "proxmox_bookstack_root_password" {
  type        = string
  description = "Password for Bookstack root user"
}