---
- name: Authenticate with NPM
  ansible.builtin.uri:
    url: "http://localhost:81/api/tokens"
    method: POST
    body_format: json
    body:
      identity: "{{ admin_email }}"
      secret: "{{ nginx_proxy_manager_admin_password }}"
    status_code: 200
  register: nginx_proxy_manager_token
  no_log: true
  tags: nginx_proxy_manager

- name: Get existing access lists
  ansible.builtin.uri:
    url: "http://localhost:81/api/nginx/access-lists?expand=clients"
    headers:
      Authorization: "Bearer {{ nginx_proxy_manager_token.json.token }}"
    status_code: 200
  register: nginx_proxy_manager_existing_access_lists
  tags: nginx_proxy_manager

- name: Set existing default access list fact
  ansible.builtin.set_fact:
    nginx_proxy_manager_existing_default_access_list: >-
      {{
        nginx_proxy_manager_existing_access_lists.json |
        selectattr('name', 'equalto', nginx_proxy_manager_default_access_list_name) |
        list | first | default({})
      }}
  tags: nginx_proxy_manager

- name: Create default access list
  ansible.builtin.uri:
    url: "http://localhost:81/api/nginx/access-lists"
    method: POST
    headers:
      Authorization: "Bearer {{ nginx_proxy_manager_token.json.token }}"
    body_format: json
    body:
      name: "{{ nginx_proxy_manager_default_access_list_name }}"
      satisfy_any: false
      clients: "{{ nginx_proxy_manager_default_access_list_clients }}"
    status_code: 201
  when: nginx_proxy_manager_existing_default_access_list == {}
  register: nginx_proxy_manager_new_default_access_list
  changed_when: true
  tags: nginx_proxy_manager

- name: Update default access list
  ansible.builtin.uri:
    url: "http://localhost:81/api/nginx/access-lists/{{ nginx_proxy_manager_existing_default_access_list.id }}"
    method: PUT
    headers:
      Authorization: "Bearer {{ nginx_proxy_manager_token.json.token }}"
    body_format: json
    body:
      name: "{{ nginx_proxy_manager_default_access_list_name }}"
      satisfy_any: false
      clients: "{{ nginx_proxy_manager_default_access_list_clients }}"
    status_code: 200
  when: >-
    nginx_proxy_manager_existing_default_access_list != {}
    and (nginx_proxy_manager_existing_default_access_list.clients | default([]) |
         map(attribute='address') | list | zip(
           nginx_proxy_manager_existing_default_access_list.clients | default([]) | map(attribute='directive') | list
         ) | map('join', ' ') | sort | list) !=
        (nginx_proxy_manager_default_access_list_clients |
         map(attribute='address') | list | zip(
           nginx_proxy_manager_default_access_list_clients | map(attribute='directive') | list
         ) | map('join', ' ') | sort | list)
  changed_when: true
  tags: nginx_proxy_manager

- name: Set default access list ID fact
  ansible.builtin.set_fact:
    nginx_proxy_manager_default_access_list_id: >-
      {{
        nginx_proxy_manager_new_default_access_list.json.id
        if (nginx_proxy_manager_new_default_access_list is not skipped)
        else nginx_proxy_manager_existing_default_access_list.id
      }}
  tags: nginx_proxy_manager
