---
- name: Authenticate with NPM
  ansible.builtin.uri:
    url: "http://localhost:81/api/tokens"
    method: POST
    body_format: json
    body:
      identity: "{{ admin_email }}"
      secret: "{{ nginx_proxy_manager_admin_password }}"
    status_code: 200
  register: nginx_proxy_manager_token
  no_log: true
  tags: nginx_proxy_manager

- name: Get existing proxy hosts
  ansible.builtin.uri:
    url: "http://localhost:81/api/nginx/proxy-hosts"
    headers:
      Authorization: "Bearer {{ nginx_proxy_manager_token.json.token }}"
    status_code: 200
  register: nginx_proxy_manager_existing_hosts
  tags: nginx_proxy_manager

- name: Delete stale proxy hosts
  ansible.builtin.uri:
    url: "http://localhost:81/api/nginx/proxy-hosts/{{ item.id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ nginx_proxy_manager_token.json.token }}"
    status_code: 200
  loop: "{{ nginx_proxy_manager_existing_hosts.json }}"
  when: >-
    (item.domain_names | first | replace('.' ~ domain, '')) not in
    (nginx_proxy_manager_proxy_hosts | map(attribute='subdomain') | list)
  changed_when: true
  tags: nginx_proxy_manager

- name: Create proxy hosts
  ansible.builtin.uri:
    url: "http://localhost:81/api/nginx/proxy-hosts"
    method: POST
    headers:
      Authorization: "Bearer {{ nginx_proxy_manager_token.json.token }}"
    body_format: json
    body:
      domain_names:
        - "{{ item.subdomain }}.{{ domain }}"
      forward_host: "{{ item.host }}"
      forward_port: "{{ item.port }}"
      forward_scheme: "{{ item.scheme | default('http') }}"
      block_exploits: true
      allow_websocket_upgrade: "{{ item.allow_websocket_upgrade | default(false) }}"
      advanced_config: "{{ item.advanced_config | default('') }}"
      access_list_id: 0
      certificate_id: "{{ nginx_proxy_manager_certificate_id }}"
      ssl_forced: true
      meta:
        letsencrypt_agree: true
        dns_challenge: false
    status_code: 201
  loop: "{{ nginx_proxy_manager_proxy_hosts }}"
  when: >-
    (item.subdomain + '.' + domain) not in
    (nginx_proxy_manager_existing_hosts.json | map(attribute='domain_names') | flatten)
  changed_when: true
  tags: nginx_proxy_manager

- name: Update proxy hosts with wildcard certificate
  ansible.builtin.uri:
    url: "http://localhost:81/api/nginx/proxy-hosts/{{ item.id }}"
    method: PUT
    headers:
      Authorization: "Bearer {{ nginx_proxy_manager_token.json.token }}"
    body_format: json
    body:
      domain_names: "{{ item.domain_names }}"
      forward_host: "{{ item.forward_host }}"
      forward_port: "{{ item.forward_port }}"
      forward_scheme: "{{ item.forward_scheme }}"
      block_exploits: "{{ item.block_exploits }}"
      allow_websocket_upgrade: >-
        {{ (nginx_proxy_manager_proxy_hosts | selectattr('subdomain', 'equalto',
        item.domain_names | first | replace('.' ~ domain, '')) | first).allow_websocket_upgrade | default(false) }}
      advanced_config: >-
        {{ (nginx_proxy_manager_proxy_hosts | selectattr('subdomain', 'equalto',
        item.domain_names | first | replace('.' ~ domain, '')) | first).advanced_config | default('') }}
      access_list_id: "{{ item.access_list_id }}"
      certificate_id: "{{ nginx_proxy_manager_certificate_id }}"
      ssl_forced: true
      meta:
        letsencrypt_agree: true
        dns_challenge: false
    status_code: 200
  loop: "{{ nginx_proxy_manager_existing_hosts.json }}"
  when: >-
    (item.domain_names | first | replace('.' ~ domain, '')) in
    (nginx_proxy_manager_proxy_hosts | map(attribute='subdomain') | list)
    and (item.certificate_id | int != nginx_proxy_manager_certificate_id | int
    or not item.ssl_forced
    or item.allow_websocket_upgrade != ((nginx_proxy_manager_proxy_hosts | selectattr('subdomain', 'equalto',
    item.domain_names | first | replace('.' ~ domain, '')) | first).allow_websocket_upgrade | default(false))
    or item.advanced_config | default('') != ((nginx_proxy_manager_proxy_hosts | selectattr('subdomain', 'equalto',
    item.domain_names | first | replace('.' ~ domain, '')) | first).advanced_config | default('')))
  changed_when: true
  tags: nginx_proxy_manager
