---
- name: Get existing proxy hosts
  ansible.builtin.uri:
    url: "http://localhost:81/api/nginx/proxy-hosts"
    method: GET
    headers:
      Authorization: "Bearer {{ nginx_proxy_manager_auth_token }}"
    status_code: 200
  register: nginx_proxy_manager_existing_hosts
  no_log: true

- name: Delete proxy host if config has changed
  ansible.builtin.uri:
    url: "http://localhost:81/api/nginx/proxy-hosts/{{ existing_host.id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ nginx_proxy_manager_auth_token }}"
    status_code: 200
  no_log: true
  loop: "{{ nginx_proxy_manager_proxy_hosts }}"
  vars:
    existing_host: >-
      {{
        nginx_proxy_manager_existing_hosts.json
        | selectattr('domain_names', 'contains', item.subdomain + '.' + domain)
        | list
        | first
        | default({})
      }}
  when:
    - existing_host | length > 0
    - existing_host.forward_scheme != (item.scheme | default('http')) or
      existing_host.forward_host != item.host or
      existing_host.forward_port != item.port

- name: Refresh existing proxy hosts after deletions
  ansible.builtin.uri:
    url: "http://localhost:81/api/nginx/proxy-hosts"
    method: GET
    headers:
      Authorization: "Bearer {{ nginx_proxy_manager_auth_token }}"
    status_code: 200
  register: nginx_proxy_manager_existing_hosts
  no_log: true

- name: Create proxy host if missing
  ansible.builtin.uri:
    url: "http://localhost:81/api/nginx/proxy-hosts"
    method: POST
    headers:
      Authorization: "Bearer {{ nginx_proxy_manager_auth_token }}"
    body_format: json
    body:
      domain_names:
        - "{{ item.subdomain }}.{{ domain }}"
      forward_scheme: "{{ item.scheme | default('http') }}"
      forward_host: "{{ item.host }}"
      forward_port: "{{ item.port }}"
      ssl_forced: true
      certificate_id: "{{ nginx_proxy_manager_wildcard_cert_id }}"
      block_exploits: true
    status_code: [200, 201]
  loop: "{{ nginx_proxy_manager_proxy_hosts }}"
  when: >-
    (nginx_proxy_manager_existing_hosts.json
    | selectattr('domain_names', 'contains', item.subdomain + '.' + domain)
    | list | length) == 0
  no_log: true
