---
all:
  children:
    physical_hosts:
      hosts:
        enterprise:
        andromeda:
        # rpi5_inactive:
        # imac_inactive:

    virtual_machines:
      children:
        lxc_containers:
          hosts:
            centaurus:
            dorothy:
        qemu_vms:
          hosts:
            norville:
    proxmox_nodes:
      hosts:
        enterprise:
    pihole_nodes:
      hosts:
        centaurus:
        andromeda:
