---
all:
  children:
    physical_hosts:
      hosts:
        enterprise:
        andromeda:
        # rpi5_inactive:
        # imac_inactive:

    virtual_machines:
      children:
        lxc_containers:
          hosts:
        # norville:
        # dorothy: # future — Homepage dashboard LXC, not yet implemented
        qemu_vms:
          hosts:
            centaurus:
    proxmox_nodes:
      hosts:
        enterprise:
    pihole_nodes:
      hosts:
        centaurus:
        andromeda:
