---
- name: Get QEMU VM list from Proxmox
  become: true
  ansible.builtin.command:
    cmd: pvesh get /nodes/{{ proxmox_api_node }}/qemu --output-format json
  register: _proxmox_qemu_list
  changed_when: false
  delegate_to: enterprise
  tags: homepage

- name: Get LXC container list from Proxmox
  become: true
  ansible.builtin.command:
    cmd: pvesh get /nodes/{{ proxmox_api_node }}/lxc --output-format json
  register: _proxmox_lxc_list
  changed_when: false
  delegate_to: enterprise
  tags: homepage

- name: Set VMID facts
  ansible.builtin.set_fact:
    homepage_proxmox_vmids:
      centaurus: >-
        {{
          ((_proxmox_qemu_list.stdout | from_json) |
          selectattr('name', 'equalto', 'centaurus') |
          map(attribute='vmid') | list + [0]) | first
        }}
      norville: >-
        {{
          ((_proxmox_qemu_list.stdout | from_json) |
          selectattr('name', 'equalto', 'norville') |
          map(attribute='vmid') | list + [0]) | first
        }}
      dorothy: >-
        {{
          ((_proxmox_lxc_list.stdout | from_json) |
          selectattr('name', 'equalto', 'dorothy') |
          map(attribute='vmid') | list + [0]) | first
        }}
  tags: homepage
