---
- name: Configure Proxmox repositories
  ansible.builtin.import_tasks: repos.yml

- name: Configure Proxmox storage
  ansible.builtin.import_tasks: storage.yml

- name: Configure DNS resolvers
  ansible.builtin.import_tasks: dns.yml

- name: Configure guest agent channel for QEMU VMs
  ansible.builtin.import_tasks: vm_guest_agent.yml
