---
# ┌─────────────────────────────────────────────────────────────────────┐
# │  Copy to secrets.yml and encrypt with ansible-vault                 │
# │                                                              /\_/\  │
# │                                                             ( ^.^ ) │
# │                                                              > ~ <  │
# └─────────────────────────────────────────────────────────────────────┘

proxmox_admin_password_salt:
