---
- name: Template local DNS entries
  become: true
  ansible.builtin.template:
    src: local-dns.conf.j2
    dest: /etc/dnsmasq.d/99-ansible-local-dns.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart pihole dns
