---
- name: Ensure pihole group exists
  become: true
  ansible.builtin.group:
    name: pihole
    state: present

- name: Ensure pihole user exists
  become: true
  ansible.builtin.user:
    name: pihole
    home: /home/pihole
    shell: /usr/sbin/nologin
    comment: Pi-hole
    group: pihole
    password: "*"
    state: present

- name: Ensure /etc/pihole directory exists
  become: true
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
    owner: pihole
    group: pihole
    mode: "0775"

- name: Template pihole.toml pre-install config
  become: true
  ansible.builtin.template:
    src: pihole.toml.j2
    dest: /etc/pihole/pihole.toml
    owner: pihole
    group: pihole
    mode: "0644"

- name: Download Pi-hole installer
  ansible.builtin.get_url:
    url: "{{ pihole_installer_url }}"
    dest: /tmp/pihole_install.sh
    mode: "0755"

- name: Run Pi-hole unattended installer # noqa: command-instead-of-shell
  become: true
  ansible.builtin.shell:
    cmd: bash /tmp/pihole_install.sh --unattended
    creates: /etc/systemd/system/pihole-FTL.service

- name: Remove Pi-hole installer script
  ansible.builtin.file:
    path: /tmp/pihole_install.sh
    state: absent

- name: Ensure Pi-hole password exists in 1Password
  # no_log: true
  ansible.builtin.include_role:
    name: onepassword
  vars:
    onepassword_action: upsert
    onepassword_item:
      title: "Pi-hole Admin Password"
      # custom_fields:
      #   - label: Notes
      #     value: "Managed by Ansible. Do not rename this item."
      #     field_type: STRING
  run_once: true

- name: Check if Pi-hole password is already correct
  ansible.builtin.uri:
    url: "http://localhost/api/auth"
    method: POST
    body_format: json
    body:
      password: >-
        {{
          onepassword_item_result.fields |
          selectattr('id', 'equalto', 'password') |
          map(attribute='value') | first
        }}
    status_code: [200, 401]
  register: pihole_auth_check
  # no_log: true

- name: Set Pi-hole web password
  become: true
  ansible.builtin.command:
    cmd: >-
      pihole setpasswd "{{
        onepassword_item_result.fields |
        selectattr('id', 'equalto', 'password') |
        map(attribute='value') | first | mandatory
      }}"
  # no_log: true
  changed_when: true
  when: pihole_auth_check.status == 401
