---
- name: Download nebula-sync binary
  ansible.builtin.get_url:
    url: "https://github.com/lovelaze/nebula-sync/releases/download/v{{ nebula_sync_version }}/nebula-sync_{{ nebula_sync_version }}_linux_amd64.tar.gz"
    dest: "/tmp/nebula-sync_{{ nebula_sync_version }}_linux_amd64.tar.gz"
    mode: "0644"
    checksum: "{{ nebula_sync_checksum }}"

- name: Extract nebula-sync binary
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/nebula-sync_{{ nebula_sync_version }}_linux_amd64.tar.gz"
    dest: /usr/local/bin
    include:
      - nebula-sync
    remote_src: true
    mode: "0755"
    owner: root
    group: root

- name: Remove nebula-sync archive
  ansible.builtin.file:
    path: "/tmp/nebula-sync_{{ nebula_sync_version }}_linux_amd64.tar.gz"
    state: absent
