---
- name: Install Pi-hole
  ansible.builtin.import_tasks: install.yml

- name: Configure DNS
  ansible.builtin.import_tasks: dns.yml

- name: Install nebula-sync
  ansible.builtin.include_tasks: nebula_sync.yml
  when: pihole_primary | default(false)
