---
# This role handles Proxmox service user creation with group and role assignment
# Parameterized to handle both opentofu and ansible service users

- name: Read Proxmox root password from 1Password
  no_log: true
  ansible.builtin.include_role:
    name: onepassword
  vars:
    onepassword_action: read
    onepassword_item:
      title: "Proxmox Root User"

- name: Create Proxmox role
  # No role management behavior in community.proxmox
  # proxmox_user_service_user_privs must be passed by the caller
  become: true
  block:
    - name: Role Check
      ansible.builtin.command: >-
        pvesh get /access/roles/{{ proxmox_user_service_user_name }} --output-format json
      register: proxmox_user_role_check
      failed_when: false
      changed_when: false

    - name: Role Creation
      ansible.builtin.command: |-
        pvesh create /access/roles -roleid {{ proxmox_user_service_user_name }} -privs '{{ proxmox_user_service_user_privs | join(",") }}'
      when: proxmox_user_role_check.rc != 0
      changed_when: true

- name: Group
  community.proxmox.proxmox_group: # noqa: args[module]
    groupid: "{{ proxmox_user_service_user_name }}"
    api_host: "{{ proxmox_api_node }}"
    api_user: root@pam
    api_password: >-
      {{
        onepassword_item_result.fields |
        selectattr('id', 'equalto', 'password') |
        map(attribute='value') | first
      }}
    validate_certs: false # REQUIRED: Bootstrap needs cert validation disabled
    state: present
    comment: Managed by Ansible

- name: Grant role to Proxmox group - {{ proxmox_user_service_user_name }}
  community.proxmox.proxmox_access_acl: # noqa: args[module]
    path: /
    roleid: "{{ proxmox_user_service_user_name }}"
    ugid: "{{ proxmox_user_service_user_name }}"
    api_host: "{{ proxmox_api_node }}"
    api_user: root@pam
    api_password: >-
      {{
        onepassword_item_result.fields |
        selectattr('id', 'equalto', 'password') |
        map(attribute='value') | first
      }}
    validate_certs: false # REQUIRED: Bootstrap needs cert validation disabled
    state: present
    type: group

- name: Create Proxmox user - {{ proxmox_user_service_user_name }}
  community.proxmox.proxmox_user: # noqa: args[module]
    comment: "Managed by Ansible"
    userid: "{{ proxmox_user_service_user_name }}@pam"
    api_host: "{{ proxmox_api_node }}"
    api_user: root@pam
    api_password: >-
      {{
        onepassword_item_result.fields |
        selectattr('id', 'equalto', 'password') |
        map(attribute='value') | first
      }}
    validate_certs: false # REQUIRED: Bootstrap needs cert validation disabled
    state: present
    groups:
      - "{{ proxmox_user_service_user_name }}"
    email: "{{ proxmox_user_service_user_name }}@510forward.space"
