---
# ┌─────────────────────────────────────────────────────────────────────┐
# │  Copy to secrets.yml and encrypt with ansible-vault                 │
# │                                                              /\_/\  │
# │                                                             ( ^.^ ) │
# │                                                              > ~ <  │
# └─────────────────────────────────────────────────────────────────────┘

nginx_proxy_manager_admin_password:
nginx_proxy_manager_cloudflare_api_token:
