---
ansible_host: 192.168.30.58
ip_address: 192.168.30.58
fqdn: norville.510forward.space
mac_address: "42:17:01:FD:72:77"

nginx_proxy_manager_certificate_domain: "*.{{ domain }}"

nginx_proxy_manager_default_access_list_name: "VLAN 30 only"
nginx_proxy_manager_default_access_list_clients:
  - address: 192.168.1.0/24
    directive: allow
  - address: 192.168.30.0/24
    directive: allow
  - address: 0.0.0.0/0
    directive: deny

proxied_services:
  - subdomain: norville
    port: 81
