---
# ┌─────────────────────────────────────────────────────────────────────┐
# │  Copy to secrets.yml and encrypt with ansible-vault                 │
# │                                                              /\_/\  │
# │                                                             ( ^.^ ) │
# │                                                              > ~ <  │
# └─────────────────────────────────────────────────────────────────────┘

operator_public_key:
onepassword_vault:
onepassword_become_user:
