---
- name: Pre-flight
  hosts: all
  gather_facts: false
  serial: 1
  tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
        timeout: 300
      delegate_to: localhost

    - name: Update known_hosts
      ansible.builtin.include_role:
        name: identity
        tasks_from: known_hosts

- name: Base configuration
  hosts: all
  vars:
    ansible_user: "{{ first_run_user | default('ansible') }}"
  roles:
    - ansible

# - name: Proxmox configuration
#   hosts: proxmox_nodes
#   roles:
#     - proxmox

- name: Pi-hole
  hosts: pihole_nodes
  vars:
    ansible_user: "{{ first_run_user | default('ansible') }}"
  roles:
    - pihole
#
- name: NGINX Proxy Manager
  hosts: norville
  vars:
    ansible_user: "{{ first_run_user | default('ansible') }}"
  roles:
    - nginx_proxy_manager
