---
pihole_dns_1: 1.1.1.1
pihole_dns_2: 1.0.0.1
pihole_listening_mode: ALL
pihole_max_db_days: 30
pihole_query_logging: true
pihole_installer_url: https://install.pi-hole.net

nebula_sync_version: "0.11.1"
nebula_sync_checksum: "sha256:c06b547ee2e1e599e6bcc5f4c0ee99042ea076df02b5964f271b41f92ad7d1ac"
nebula_sync_run_gravity: false
