---
- name: Install qemu-guest-agent
  become: true
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
  tags: proxmox_vm_guest_agent

- name: Check virtio-serial channel is present
  ansible.builtin.stat:
    path: /dev/virtio-ports/org.qemu.guest_agent.0
  register: _proxmox_virtio_channel
  tags: proxmox_vm_guest_agent

- name: Enable qemu-guest-agent service
  become: true
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: "{{ 'started' if _proxmox_virtio_channel.stat.exists else 'stopped' }}"
  tags: proxmox_vm_guest_agent
